Refactor CI workflow to run unit tests and validate XML report

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -10,8 +10,7 @@ on:
     branches: [ "master" ]
 
 jobs:
-  build:
-
+  test:
     runs-on: macos-latest
 
     steps:
@@ -19,7 +18,13 @@ jobs:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable
-    - name: Build
-      run: swift build -v
-    # - name: Run tests
-    #   run: swift test -v
+    - name: Run Unit Test
+      run: swift test --xunit-output report.xml
+    - name: Validate XML Report
+      run: |
+        if [ $(xmllint --xpath "sum(//testsuite/@errors)" report.xml) -ne 0 ] || \
+          [ $(xmllint --xpath "sum(//testsuite/@failures)" report.xml) -ne 0 ] || \
+          [ $(xmllint --xpath "sum(//testsuite/@skipped)" report.xml) -ne 0 ]; then
+          echo "Test failures detected in XML report"
+          exit 1
+        fi
